# k8s/01-storage/kafka-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Use Minikube's default
  resources:
    requests:
      storage: 10Gi