# k8s/01-storage/uploads-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard  # Use Minikube's default
  resources:
    requests:
      storage: 20Gi