# k8s/02-secrets/auth-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: microservices
type: Opaque
stringData:
  SYSTEM_ADMIN_EMAIL: "anthonyalando8@gmail.com"
  SYSTEM_ADMIN_PASSWORD: "96211581#Aa"
  JWT_AUDIENCE: "pxyz-clients"
  JWT_ISSUER: "auth-service"
  JWT_ACCESS_TTL: "24h"