# k8s/02-secrets/db-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: microservices
type: Opaque
stringData:
  DB_HOST: "host.docker.internal"  # For Docker Desktop, or your actual DB host
  DB_PORT: "5432"
  DB_USER: "sam"
  DB_PASSWORD: "Kenya_2025!"
  DB_NAME: "pxyz_user"
  DB_CONN: "postgres://sam:Kenya_2025!@host.docker.internal:5432/pxyz_user"