# k8s/02-secrets/email-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: email-secrets
  namespace: microservices
type: Opaque
stringData:
  SMTP_HOST: "mail.derinance.com"
  SMTP_PORT: "465"
  SMTP_USER: "no_reply@derinance.com"
  SMTP_PASSWORD: "B-e02G#D-T7O*8Qe"