# k8s/02-secrets/sms-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sms-secrets
  namespace: microservices
type: Opaque
stringData:
  WA_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJieXVmU1hvSnFHY2NPcWNXOW82NXRWMWI4WVdsMEd3aSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU2NzQ3MjMzfQ.npCbVvXb2i_gAkBr3iXi_spHVbBG4l_ZXgqevm8jfjg"
  WA_URL: "https://www.whatsupsender.co.ke"
  WA_SENDER: "254792207010"
  SMS_URL: "https://smsportal.hostpinnacle.co.ke/SMSApi/send"
  SMS_KEY: ""
  SMS_SENDER: "DERINANCE"
  SMS_USER_ID: "samderinance"
  SMS_PASSWORD: "Fbq75Ttz"