# k8s/07-ingress/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: microservices
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Auth Service
      - path: /api/v1/auth(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 8001
      - path: /api/v1/oauth2(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: auth-service
            port:
              number: 8001
      
      # Session Service
      - path: /api/v1/session(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: session-service
            port:
              number: 8002
      
      # OTP Service
      - path: /api/v1/otp(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: otp-service
            port:
              number: 8003
      
      # Account Service
      - path: /api/v1/account(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: account-service
            port:
              number: 8004
      
      # KYC Service
      - path: /api/v1/kyc(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kyc-service
            port:
              number: 8005
      
      # Audit Service
      - path: /api/v1/audit(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: audit-service
            port:
              number: 8008
      
      # Email Service
      - path: /api/v1/email(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: email-service
            port:
              number: 8011
      
      # SMS Service
      - path: /api/v1/sms(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sms-service
            port:
              number: 8012
      
      # Notification Service
      - path: /api/v1/user/notifications(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: notification-service
            port:
              number: 8013
      
      # Core Service
      - path: /api/v1/core(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: core-service
            port:
              number: 8051
      
      # User Access Service
      - path: /api/v1/urbac(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: u-access-service
            port:
              number: 8031