# k8s/05-services/account-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: microservices
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: account-service:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8004
          name: grpc
        env:
        - name: GRPC_ADDR
          value: ":8004"
        - name: DB_CONN
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_CONN
        - name: REDIS_ADDR
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: REDIS_ADDR
        - name: EMAIL_SVC_ADDR
          value: "email-service:8011"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: microservices
spec:
  selector:
    app: account-service
  ports:
  - port: 8004
    targetPort: 8004
    name: grpc
  type: ClusterIP